// <auto-generated />
namespace BanHangThoiTrangMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update25052023 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update25052023));
        
        string IMigrationMetadata.Id
        {
            get { return "202305251343413_update25052023"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
